networking, gateway: bash has weird error semantics around subshells

diff --git a/roles/gateway/templates/networkd-dispatcher/gateway-home/configured.d/telekom b/roles/gateway/templates/networkd-dispatcher/gateway-home/configured.d/telekom
--- a/roles/gateway/templates/networkd-dispatcher/gateway-home/configured.d/telekom
+++ b/roles/gateway/templates/networkd-dispatcher/gateway-home/configured.d/telekom
@@ -6,6 +6,7 @@
 # journalctl --follow --unit networkd-dispatcher.service
 
 set -euo pipefail
+shopt -s inherit_errexit
 
 [[ "$IFACE" == {{ interfaces.telekom.device | mandatory | quote }} ]] || exit  0
 
@@ -19,10 +20,8 @@ printf 'ddclient failed, attempting manual DynDNS update\n'
 resolve() {
   local host="${1?Need host to resolve}"
 
-  ip="$(dig +short @8.8.8.8 A "$host")"
-
-  if [[ -z "$ip" ]]; then
-    >&2 printf 'Could not resolve %s\n' "$host"
+  if ! ip="$(dig +short @8.8.8.8 A "$host")" || [[ -z "$ip" ]]; then
+    >&2 printf 'Could not resolve %s: %s\n' "$host" "$ip"
     return 1
   fi
 
diff --git a/roles/gateway/templates/wireguard-resolve-endpoint/wireguard-resolve-endpoint b/roles/gateway/templates/wireguard-resolve-endpoint/wireguard-resolve-endpoint
--- a/roles/gateway/templates/wireguard-resolve-endpoint/wireguard-resolve-endpoint
+++ b/roles/gateway/templates/wireguard-resolve-endpoint/wireguard-resolve-endpoint
@@ -2,7 +2,9 @@
 
 # Reference:
 # https://git.zx2c4.com/WireGuard/tree/contrib/examples/reresolve-dns/reresolve-dns.sh
+
 set -euo pipefail
+shopt -s inherit_errexit
 
 if ! hash wg 2> /dev/null; then
   >&2 printf 'wg not found\n'
@@ -50,10 +52,8 @@ update-endpoint-ip() {
       return
     fi
 
-    ip="$(dig +short A "$endpoint" @1.1.1.1)"
-
-    if [[ -z "$ip" ]]; then
-     >&2 printf 'Peer %s: Could not resolve %s\n' "$peer" "$endpoint"
+    if ! ip="$(dig +short @8.8.8.8 A "$endpoint")" || [[ -z "$ip" ]]; then
+     >&2 printf 'Peer %s: Could not resolve %s: %s\n' "$peer" "$endpoint" "$ip"
      return 1
     fi
 
